name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Получаем код
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Устанавливаем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3️⃣ Устанавливаем зависимости
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Проверяем типы (TypeScript)
      - name: Type check
        run: npm run typecheck --if-present

      # 5️⃣ Запускаем линтер
      - name: Lint
        run: npm run lint --if-present

      # 6️⃣ Тесты
      - name: Run tests
        run: npm test --if-present

      # 7️⃣ Сборка проекта
      - name: Build
        run: npm run build
